name: app_motoboy
description: App para motoboys do Gerenciador de Motoboys

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true